/** Generates the catalogue, rate-card and sequence seed migrations from the
 *  TypeScript domain definitions, so the database and the pricing engine can
 *  never drift apart. Run `npm run seed:generate` after changing either.
 *
 *  The generated files are committed — a migration that only exists when a
 *  script has been run is not a migration. */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { ITEMS, ROOMS } from "../src/domain/inventory/catalogue";
import { defaultRateCard } from "../src/domain/pricing/default-rate-card";
import { SEQUENCES } from "../src/domain/sequences/definitions";
import type { ServiceCategory } from "../src/domain/pricing/types";

const q = (value: string): string => `'${value.replace(/'/g, "''")}'`;
const dir = resolve(import.meta.dirname, "../supabase/migrations");

// ── 0012: rooms and items ───────────────────────────────────────────────────
const catalogue = [
  "-- GENERATED by scripts/generate-seed-sql.ts from",
  "-- src/domain/inventory/catalogue.ts. Do not edit by hand: the pricing",
  "-- engine reads the TypeScript, so an edit here would silently diverge.",
  "",
  "insert into rooms (slug, name, icon, sort_order) values",
  ROOMS.map((r) => `  (${q(r.slug)}, ${q(r.name)}, ${q(r.icon)}, ${r.sortOrder})`).join(",\n") + ";",
  "",
  "insert into items (slug, name, room_slug, icon, volume_ft3, crew_minutes, is_fragile, requires_dismantle, handling) values",
  ITEMS.map(
    (i) =>
      `  (${q(i.slug)}, ${q(i.name)}, ${q(i.roomSlug)}, ${q(i.icon)}, ${i.volumeFt3.toFixed(2)}, ${i.crewMinutes}, ${i.isFragile}, ${i.requiresDismantle}, ${q(i.handling)})`,
  ).join(",\n") + ";",
  "",
].join("\n");
writeFileSync(resolve(dir, "0013_seed_catalogue.sql"), catalogue);

// ── 0013: rate cards ────────────────────────────────────────────────────────
const CATEGORIES: readonly ServiceCategory[] = [
  "residential",
  "commercial",
  "office",
  "specialist",
  "clearance",
  "storage",
];

const rateCardRows = CATEGORIES.map((category) => {
  const card = defaultRateCard("__brand__", category);
  const { id, brandSlug, serviceCategory, currency, effectiveFrom, provisional, ...rules } = card;
  void id;
  void brandSlug;
  void currency;
  return `  (${q(serviceCategory)}, ${q(effectiveFrom)}, ${provisional}, ${q(JSON.stringify(rules))}::jsonb)`;
}).join(",\n");

const rateCards = [
  "-- GENERATED by scripts/generate-seed-sql.ts from",
  "-- src/domain/pricing/default-rate-card.ts.",
  "--",
  "-- VALUE REQUIRED FROM BUSINESS: every figure in these cards is provisional.",
  "-- `provisional = true` puts a PROVISIONAL PRICING watermark on every quote",
  "-- PDF generated from them. See DECISIONS.md §2 before clearing it.",
  "",
  "insert into rate_cards (brand_id, service_category, effective_from, provisional, rules)",
  "select b.id, v.category::customer_type, v.effective_from::date, v.provisional, v.rules",
  "from brands b",
  "cross join (values",
  rateCardRows,
  ") as v(category, effective_from, provisional, rules);",
  "",
].join("\n");
writeFileSync(resolve(dir, "0014_seed_rate_cards.sql"), rateCards);

// ── 0015: sequences and their steps ─────────────────────────────────────────
const sequenceRows = SEQUENCES.map(
  (s) => `  (${q(s.key)}, ${q(s.name)}, ${q(s.description)})`,
).join(",\n");

const stepRows = SEQUENCES.flatMap((s) =>
  s.steps.map(
    (step) =>
      `  (${q(s.key)}, ${step.order}, ${step.delayMinutes}, ${q(step.channel)}, ${q(step.templateKey)}, ` +
      `array[${step.stopConditions.map(q).join(",")}]::text[], ${step.respectQuietHours}, ${step.countsTowardFrequencyCap})`,
  ),
).join(",\n");

const sequences = [
  "-- GENERATED by scripts/generate-seed-sql.ts from",
  "-- src/domain/sequences/definitions.ts.",
  "--",
  "-- Platform defaults: brand_id is null, so every brand inherits them. A brand",
  "-- overrides one by inserting its own row with the same key.",
  "",
  "insert into sequences (brand_id, key, name, description)",
  "select null, v.key, v.name, v.description",
  "from (values",
  sequenceRows,
  ") as v(key, name, description);",
  "",
  "insert into sequence_steps (sequence_id, step_order, delay_minutes, channel, template_key, stop_conditions, respect_quiet_hours, counts_toward_frequency_cap)",
  "select s.id, v.step_order, v.delay_minutes, v.channel::message_channel, v.template_key, v.stop_conditions, v.respect_quiet_hours, v.counts_toward_cap",
  "from (values",
  stepRows,
  ") as v(sequence_key, step_order, delay_minutes, channel, template_key, stop_conditions, respect_quiet_hours, counts_toward_cap)",
  "join sequences s on s.key = v.sequence_key and s.brand_id is null;",
  "",
].join("\n");
writeFileSync(resolve(dir, "0016_seed_sequences.sql"), sequences);

console.log("Generated 0013_seed_catalogue.sql, 0014_seed_rate_cards.sql, 0016_seed_sequences.sql");
