-- GENERATED by scripts/generate-seed-sql.ts from
-- src/domain/sequences/definitions.ts.
--
-- Platform defaults: brand_id is null, so every brand inherits them. A brand
-- overrides one by inserting its own row with the same key.

insert into sequences (brand_id, key, name, description)
select null, v.key, v.name, v.description
from (values
  ('lead_acknowledgement', 'Enquiry acknowledgement', 'Sent immediately, at any hour. An enquiry that arrives at 2 a.m. is answered at 2 a.m. — this is the fix for overnight lead loss.'),
  ('quote_chase', '48-hour quote chase', 'The core of the brief: a quote viewed but not accepted within 48 hours is chased, then chased again, then handed to a human.'),
  ('quote_expiry_warning', 'Quote expiry warning', 'Warns before a fixed price lapses, rather than letting it lapse silently.'),
  ('abandoned_inventory', 'Abandoned inventory recovery', 'Recovers a half-finished inventory from the web form.'),
  ('booking_confirmation', 'Booking confirmation', 'Transactional. Goes out immediately regardless of hour or cap.'),
  ('pre_move_reminder', 'Pre-move reminder', 'Three days out, then the evening before.'),
  ('payment_retry', 'Payment retry', 'A failed or expired payment never silently cancels a booking — it chases, then raises a task.'),
  ('review_request', 'Review request', 'Sent the day after completion, while the move is fresh. Review lag is on the problem list; the fix is timing, not nagging.')
) as v(key, name, description);

insert into sequence_steps (sequence_id, step_order, delay_minutes, channel, template_key, stop_conditions, respect_quiet_hours, counts_toward_frequency_cap)
select s.id, v.step_order, v.delay_minutes, v.channel::message_channel, v.template_key, v.stop_conditions, v.respect_quiet_hours, v.counts_toward_cap
from (values
  ('lead_acknowledgement', 1, 0, 'email', 'lead_acknowledgement', array['unsubscribed','manual_stop']::text[], false, false),
  ('quote_chase', 1, 2880, 'email', 'quote_chase_1', array['unsubscribed','manual_stop','lead_lost','quote_accepted','customer_replied','quote_expired']::text[], true, true),
  ('quote_chase', 2, 5760, 'whatsapp', 'quote_chase_2', array['unsubscribed','manual_stop','lead_lost','quote_accepted','customer_replied','quote_expired']::text[], true, true),
  ('quote_chase', 3, 10080, 'task', 'quote_chase_call_task', array['unsubscribed','manual_stop','lead_lost','quote_accepted','quote_expired']::text[], false, false),
  ('quote_expiry_warning', 1, 0, 'email', 'quote_expiry_warning', array['unsubscribed','manual_stop','lead_lost','quote_accepted','quote_expired']::text[], true, true),
  ('abandoned_inventory', 1, 120, 'email', 'abandoned_inventory', array['unsubscribed','manual_stop','lead_lost','quote_accepted','customer_replied']::text[], true, true),
  ('booking_confirmation', 1, 0, 'email', 'booking_confirmation', array['manual_stop']::text[], false, false),
  ('pre_move_reminder', 1, 0, 'email', 'pre_move_reminder_3d', array['manual_stop','unsubscribed']::text[], true, false),
  ('pre_move_reminder', 2, 2880, 'whatsapp', 'pre_move_reminder_1d', array['manual_stop','unsubscribed']::text[], true, false),
  ('payment_retry', 1, 60, 'email', 'payment_retry_1', array['payment_received','manual_stop']::text[], true, false),
  ('payment_retry', 2, 1440, 'task', 'payment_retry_task', array['payment_received','manual_stop']::text[], false, false),
  ('review_request', 1, 1440, 'email', 'review_request_1', array['unsubscribed','manual_stop','lead_lost','customer_replied']::text[], true, true),
  ('review_request', 2, 7200, 'whatsapp', 'review_request_2', array['unsubscribed','manual_stop','lead_lost','customer_replied']::text[], true, true)
) as v(sequence_key, step_order, delay_minutes, channel, template_key, stop_conditions, respect_quiet_hours, counts_toward_cap)
join sequences s on s.key = v.sequence_key and s.brand_id is null;
